### ISSUE TITLE
Vagrant: elasticsearch: unrecognized service

### ISSUE THREAD

**Issue by hoxu** [scragg0x/realms-wiki#123]
Vagrant up seems to fail with newest git (bca09fa):

```
==> default: Cleaning up...
==> default: Installing start scripts
==> default: elasticsearch: unrecognized service
==> default: Traceback (most recent call last):
==> default:   File "/home/vagrant/.venv/bin/realms-wiki", line 9, in <module>
==> default:     load_entry_point('realms-wiki==0.6.1', 'console_scripts', 'realms-wiki')()
==> default:   File "/home/vagrant/.venv/local/lib/python2.7/site-packages/pkg_resources.py", line 353, in load_entry_point
==> default:     return get_distribution(dist).load_entry_point(group, name)
==> default:   File "/home/vagrant/.venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2321, in load_entry_point
==> default:     return ep.load()
==> default:   File "/home/vagrant/.venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2048, in load
==> default:     entry = __import__(self.module_name, globals(),globals(), ['__name__'])
==> default:   File "/vagrant/realms/commands.py", line 14, in <module>
==> default:     app = create_app()
==> default:   File "/vagrant/realms/__init__.py", line 208, in create_app
==> default:     app.discover()
==> default:   File "/vagrant/realms/__init__.py", line 67, in discover
==> default:     sources = __import__('%s.%s' % (import_name, module_name), fromlist=fromlist)
==> default:   File "/vagrant/realms/modules/auth/commands.py", line 3, in <module>
==> default:     Interface summary:
==> default: ImportError: cannot import name User
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by scragg0x** [comment]
I removed elaticsearch from the install script.  Also you will need to clean .pyc files.  That's causing the crash.

`find *.pyc | xargs rm`
