### ISSUE TITLE
Docker run fails

### ISSUE THREAD

**Issue by RSully** [scragg0x/realms-wiki#164]
Using the following command:

```
docker run -p 5001:5000 realms/realms-wiki:0.8.0
```

**Comment by webpigeon** [comment]
I have the same problem, running the following
```
docker run --name realms-wiki -p 5000:5000 -d realms/realms-wiki:0.8.0
```

Causes the container to fail, with the following log:

```
webpigeon@hammer:~$ docker logs realms-wiki
[2016-07-20 15:57:12 +0000] [8] [INFO] Starting gunicorn 19.3.0
[2016-07-20 15:57:12 +0000] [8] [INFO] Listening at: http://0.0.0.0:5000 (8)
[2016-07-20 15:57:12 +0000] [8] [INFO] Using worker: gevent
[2016-07-20 15:57:12 +0000] [13] [INFO] Booting worker with pid: 13
[2016-07-20 15:57:12 +0000] [14] [INFO] Booting worker with pid: 14
[2016-07-20 15:57:12 +0000] [15] [INFO] Booting worker with pid: 15
[2016-07-20 15:57:12 +0000] [13] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 192, in init_process
    super(GeventWorker, self).init_process()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/util.py", line 366, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/wiki/realms-wiki/realms/__init__.py", line 167, in create_app
    app.config.from_object('realms.config.conf')
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/werkzeug/utils.py", line 418, in import_string
    __import__(import_name)
  File "/home/wiki/realms-wiki/realms/config/__init__.py", line 218, in <module>
    conf = Config()
  File "/home/wiki/realms-wiki/realms/config/__init__.py", line 147, in __init__
    setattr(self, k, v)
AttributeError: can't set attribute
Traceback (most recent call last):
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 192, in init_process
    super(GeventWorker, self).init_process()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/util.py", line 366, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/wiki/realms-wiki/realms/__init__.py", line 167, in create_app
    app.config.from_object('realms.config.conf')
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/werkzeug/utils.py", line 418, in import_string
    __import__(import_name)
  File "/home/wiki/realms-wiki/realms/config/__init__.py", line 218, in <module>
    conf = Config()
  File "/home/wiki/realms-wiki/realms/config/__init__.py", line 147, in __init__
    setattr(self, k, v)
AttributeError: can't set attribute
[2016-07-20 15:57:12 +0000] [13] [INFO] Worker exiting (pid: 13)
[2016-07-20 15:57:12 +0000] [15] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 192, in init_process
    super(GeventWorker, self).init_process()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/util.py", line 366, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/wiki/realms-wiki/realms/__init__.py", line 167, in create_app
    app.config.from_object('realms.config.conf')
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/werkzeug/utils.py", line 418, in import_string
    __import__(import_name)
  File "/home/wiki/realms-wiki/realms/config/__init__.py", line 218, in <module>
    conf = Config()
  File "/home/wiki/realms-wiki/realms/config/__init__.py", line 147, in __init__
    setattr(self, k, v)
AttributeError: can't set attribute
Traceback (most recent call last):
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 192, in init_process
    super(GeventWorker, self).init_process()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/util.py", line 366, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/wiki/realms-wiki/realms/__init__.py", line 167, in create_app
    app.config.from_object('realms.config.conf')
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/werkzeug/utils.py", line 418, in import_string
    __import__(import_name)
  File "/home/wiki/realms-wiki/realms/config/__init__.py", line 218, in <module>
    conf = Config()
  File "/home/wiki/realms-wiki/realms/config/__init__.py", line 147, in __init__
    setattr(self, k, v)
AttributeError: can't set attribute
[2016-07-20 15:57:12 +0000] [15] [INFO] Worker exiting (pid: 15)
[2016-07-20 15:57:12 +0000] [14] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 192, in init_process
    super(GeventWorker, self).init_process()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/util.py", line 366, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/wiki/realms-wiki/realms/__init__.py", line 167, in create_app
    app.config.from_object('realms.config.conf')
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/werkzeug/utils.py", line 418, in import_string
    __import__(import_name)
  File "/home/wiki/realms-wiki/realms/config/__init__.py", line 218, in <module>
    conf = Config()
  File "/home/wiki/realms-wiki/realms/config/__init__.py", line 147, in __init__
    setattr(self, k, v)
AttributeError: can't set attribute
Traceback (most recent call last):
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 192, in init_process
    super(GeventWorker, self).init_process()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/util.py", line 366, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/wiki/realms-wiki/realms/__init__.py", line 167, in create_app
    app.config.from_object('realms.config.conf')
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/werkzeug/utils.py", line 418, in import_string
    __import__(import_name)
  File "/home/wiki/realms-wiki/realms/config/__init__.py", line 218, in <module>
    conf = Config()
  File "/home/wiki/realms-wiki/realms/config/__init__.py", line 147, in __init__
    setattr(self, k, v)
AttributeError: can't set attribute
[2016-07-20 15:57:12 +0000] [14] [INFO] Worker exiting (pid: 14)
Traceback (most recent call last):
  File "/home/wiki/realms-wiki/.venv/bin/gunicorn", line 11, in <module>
    sys.exit(run())

[2016-07-20 15:57:21 +0000] [9] [INFO] Starting gunicorn 19.3.0
[2016-07-20 15:57:21 +0000] [9] [INFO] Listening at: http://0.0.0.0:5000 (9)
[2016-07-20 15:57:21 +0000] [9] [INFO] Using worker: gevent
[2016-07-20 15:57:21 +0000] [14] [INFO] Booting worker with pid: 14
[2016-07-20 15:57:21 +0000] [15] [INFO] Booting worker with pid: 15
[2016-07-20 15:57:21 +0000] [20] [INFO] Booting worker with pid: 20
[2016-07-20 15:57:21 +0000] [14] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 192, in init_process
    super(GeventWorker, self).init_process()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/util.py", line 366, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/wiki/realms-wiki/realms/__init__.py", line 167, in create_app
    app.config.from_object('realms.config.conf')
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/werkzeug/utils.py", line 418, in import_string
    __import__(import_name)
  File "/home/wiki/realms-wiki/realms/config/__init__.py", line 218, in <module>
    conf = Config()
  File "/home/wiki/realms-wiki/realms/config/__init__.py", line 147, in __init__
    setattr(self, k, v)
AttributeError: can't set attribute
Traceback (most recent call last):
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 192, in init_process
    super(GeventWorker, self).init_process()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/util.py", line 366, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/wiki/realms-wiki/realms/__init__.py", line 167, in create_app
    app.config.from_object('realms.config.conf')
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/werkzeug/utils.py", line 418, in import_string
    __import__(import_name)
  File "/home/wiki/realms-wiki/realms/config/__init__.py", line 218, in <module>
    conf = Config()
  File "/home/wiki/realms-wiki/realms/config/__init__.py", line 147, in __init__
    setattr(self, k, v)
AttributeError: can't set attribute
[2016-07-20 15:57:21 +0000] [14] [INFO] Worker exiting (pid: 14)
[2016-07-20 15:57:21 +0000] [15] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 192, in init_process
    super(GeventWorker, self).init_process()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/util.py", line 366, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/wiki/realms-wiki/realms/__init__.py", line 167, in create_app
    app.config.from_object('realms.config.conf')
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/werkzeug/utils.py", line 418, in import_string
    __import__(import_name)
  File "/home/wiki/realms-wiki/realms/config/__init__.py", line 218, in <module>
    conf = Config()
  File "/home/wiki/realms-wiki/realms/config/__init__.py", line 147, in __init__
    setattr(self, k, v)
AttributeError: can't set attribute
Traceback (most recent call last):
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 192, in init_process
    super(GeventWorker, self).init_process()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/util.py", line 366, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/wiki/realms-wiki/realms/__init__.py", line 167, in create_app
    app.config.from_object('realms.config.conf')
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/werkzeug/utils.py", line 418, in import_string
    __import__(import_name)
  File "/home/wiki/realms-wiki/realms/config/__init__.py", line 218, in <module>
    conf = Config()
  File "/home/wiki/realms-wiki/realms/config/__init__.py", line 147, in __init__
    setattr(self, k, v)
AttributeError: can't set attribute
[2016-07-20 15:57:21 +0000] [15] [INFO] Worker exiting (pid: 15)
[2016-07-20 15:57:21 +0000] [20] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 192, in init_process
    super(GeventWorker, self).init_process()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/util.py", line 366, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/wiki/realms-wiki/realms/__init__.py", line 167, in create_app
    app.config.from_object('realms.config.conf')
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/werkzeug/utils.py", line 418, in import_string
    __import__(import_name)
  File "/home/wiki/realms-wiki/realms/config/__init__.py", line 218, in <module>
    conf = Config()
  File "/home/wiki/realms-wiki/realms/config/__init__.py", line 147, in __init__
    setattr(self, k, v)
AttributeError: can't set attribute
Traceback (most recent call last):
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 192, in init_process
    super(GeventWorker, self).init_process()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/util.py", line 366, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/wiki/realms-wiki/realms/__init__.py", line 167, in create_app
    app.config.from_object('realms.config.conf')
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/werkzeug/utils.py", line 418, in import_string
    __import__(import_name)
  File "/home/wiki/realms-wiki/realms/config/__init__.py", line 218, in <module>
    conf = Config()
  File "/home/wiki/realms-wiki/realms/config/__init__.py", line 147, in __init__
    setattr(self, k, v)
AttributeError: can't set attribute
[2016-07-20 15:57:21 +0000] [20] [INFO] Worker exiting (pid: 20)
Traceback (most recent call last):
  File "/home/wiki/realms-wiki/.venv/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 189, in run
    super(Application, self).run()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 201, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 297, in halt
    self.stop()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 342, in stop
    time.sleep(0.1)
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 214, in handle_chld
    self.reap_workers()
  File "/home/wiki/realms-wiki/.venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 459, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```

**Comment by Michael-F-Bryan** [comment]
I'm having the same issue. It looks like on like 147 of realms-wiki/realms/config/__init__.py you're trying to set an attribute that isn't allowed. 

I'm thinking in the Config.read() method, either one of the environment variables or one of the keys in the json config file, "realms-wiki.json", is dodgy. I'll try to see if I can fix it myself and submit a pull request, but it could be something to do with the docker file and hard to reproduce.

**Comment by dlip** [comment]
Same here :-1:

**Comment by gazpachoking** [comment]
I don't use docker, but at first glance my guess is setting `SQLALCHEMY_DATABASE_URI` is the problem here: https://github.com/scragg0x/realms-wiki/blob/master/docker/Dockerfile#L31

That setting appears to have 2 different names, but only `DB_URI` is writable now. Not sure why there are 2 names, and which one is meant to be used. @scragg0x Any reason for this alias you remember? Should we just remove one of them?

Deleting line 31 of the docker file should get everything working properly.

**Comment by gazpachoking** [comment]
Actually, I just went ahead and made the change 2a8bf2c511ecd

**Comment by dlip** [comment]
Thanks, when do you plan to push this to dockerhub?

**Comment by gazpachoking** [comment]
> Thanks, when do you plan to push this to dockerhub?

@scragg0x will have to field that question.

**Comment by scragg0x** [comment]
I pushed an updated image.
