### ISSUE TITLE
ImportError: No module named click (vagrant install)

### ISSUE THREAD

**Issue by tram0004** [scragg0x/realms-wiki#203]
Default vagrant install has this problem:

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ pwd
/vagrant
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ sudo ./realms-wiki stop
Traceback (most recent call last):
  File "./realms-wiki", line 3, in <module>
    from realms.commands import cli
  File "/vagrant/realms/__init__.py", line 17, in <module>
    import click
ImportError: No module named click
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ sudo ./realms-wiki help
Traceback (most recent call last):
  File "./realms-wiki", line 3, in <module>
    from realms.commands import cli
  File "/vagrant/realms/__init__.py", line 17, in <module>
    import click
ImportError: No module named click
vagrant@vagrant-ubuntu-trusty-64:/vagrant$
```

**Comment by tram0004** [comment]
OK, so you get around this by doing a `. ~/.venv/bin/activate` first.
