### ISSUE TITLE
Unable to install: no module pbr.pbr_json

### ISSUE THREAD

**Issue by magic890** [scragg0x/realms-wiki#56]
Hi,

I'm trying to install the wiki and I'm getting this error after running `pip install realms-wiki`:

    Installed /tmp/easy_install-OsO0yD/traceback2-1.4.0/pbr-1.2.0-py2.6.egg

    Installed /tmp/pip-build-root/unittest2/traceback2-1.4.0-py2.6.egg

    Searching for six>=1.4

    Reading http://pypi.python.org/simple/six/

    Best match: six 1.9.0

    Downloading https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz#md5=476881ef4012262dfc8adc645ee786c4

    Processing six-1.9.0.tar.gz

    Running six-1.9.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Ubg0Jy/six-1.9.0/egg-dist-tmp-kANAIq

    Traceback (most recent call last):

      File "<string>", line 16, in <module>

      File "/tmp/pip-build-root/unittest2/setup.py", line 87, in <module>

        setup(**params)

      File "/usr/lib64/python2.6/distutils/core.py", line 113, in setup

        _setup_distribution = dist = klass(attrs)

      File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 221, in __init__

        self.fetch_build_eggs(attrs.pop('setup_requires'))

      File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 245, in fetch_build_eggs

        parse_requirements(requires), installer=self.fetch_build_egg

      File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 538, in resolve

        dist = best[req.key] = env.best_match(req, self, installer)

      File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 780, in best_match

        return self.obtain(req, installer) # try and download/install

      File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 792, in obtain

        return installer(requirement)

      File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 293, in fetch_build_egg

        return cmd.easy_install(req)

      File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 472, in easy_install

        return self.install_item(spec, dist.location, tmpdir, deps)

      File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 502, in install_item

        dists = self.install_eggs(spec, download, tmpdir)

      File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 681, in install_eggs

        return self.build_and_install(setup_script, setup_base)

      File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 958, in build_and_install

        self.run_setup(setup_script, setup_base, args)

      File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 947, in run_setup

        run_setup(setup_script, args)

      File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 29, in run_setup

        lambda: execfile(

      File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 70, in run

        return func()

      File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 31, in <lambda>

        {'__file__':setup_script, '__name__':'__main__'}

      File "setup.py", line 31, in <module>

      File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup

        dist.run_commands()

      File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands

        self.run_command(cmd)

      File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command

        cmd_obj.run()

      File "/usr/lib/python2.6/site-packages/setuptools/command/bdist_egg.py", line 167, in run

        self.run_command("egg_info")

      File "/usr/lib64/python2.6/distutils/cmd.py", line 333, in run_command

        self.distribution.run_command(command)

      File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command

        cmd_obj.run()

      File "<string>", line 11, in replacement_run

      File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load

        entry = __import__(self.module_name, globals(),globals(), ['__name__'])

    ImportError: No module named pbr.pbr_json

    ----------------------------------------
    Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-root/unittest2
    Storing complete log in /root/.pip/pip.log

[Here the full log](https://dl.dropboxusercontent.com/u/24915153/GitHub/scragg0x%3Arealms-wiki/unable%20to%20install%20on%20centos%20pip.log).

How can I solve this issue?

**Comment by magic890** [comment]
I'm on CentOS 6.
Fixed installing `pbr` module manually via: `yum install python-pbr`.
